version: '3'
services:

  mongodb1:  
    image: mvertes/alpine-mongo:3.4.10-0
    container_name: mongodb1
    hostname: mongodb1
    ports: ["27017:27017","28017:28017"]
    command: mongod --noprealloc --smallfiles --replSet rs0 --dbpath /data/db --nojournal --oplogSize 16 --noauth --rest
    environment:
      TERM: xterm    
  
  mongodb2:  
    image: mvertes/alpine-mongo:3.4.10-0
    container_name: mongodb2
    hostname: mongodb2
    ports: ["27018:27017","28018:28017"]  
    command: mongod --noprealloc --smallfiles --replSet rs0 --dbpath /data/db --nojournal --oplogSize 16 --noauth --rest
    environment:
      TERM: xterm    
  
  mongodb3:  
    image: mvertes/alpine-mongo:3.4.10-0
    container_name: mongodb3
    hostname: mongodb3  
    ports: ["27019:27017","28019:28017"]      
    command: mongod --noprealloc --smallfiles --replSet rs0 --dbpath /data/db --nojournal --oplogSize 16 --noauth --rest
    environment:
      TERM: xterm    
  
  mongodbarbiter:  
    image: mvertes/alpine-mongo:3.4.10-0
    container_name: mongodbarbiter
    hostname: mongodbarbiter
    ports: ["27020:27017","28020:28017"]
    command: mongod --noprealloc --smallfiles --replSet rs0 --dbpath /data/db --nojournal --oplogSize 16 --noauth --rest
    environment:
      TERM: xterm    
  
  client:  
    build: ./setup
    container_name: client
    hostname: client
    links: [mongodb1,mongodb2,mongodb3,mongodbarbiter]
    environment:
      MONGODB_USER: test
      MONGODB_PASSWORD: "@tesT123"
      MONGODB_DB: testdb    